# Generated by Django 5.2.5 on 2025-08-25 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_productreview'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productreview',
            unique_together=set(),
        ),
    ]
