# Generated by Django 5.2.5 on 2025-08-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_productreview_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ai_tags',
            field=models.TextField(blank=True, help_text='AI-generated comma-separated tags for smart searching', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.CharField(blank=True, help_text='AI-generated SEO meta description', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='AI-generated comma-separated SEO keywords', max_length=255, null=True),
        ),
    ]
