# Generated by Django 5.2.5 on 2025-08-27 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_product_ai_tags_product_meta_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='meta_description',
        ),
    ]
