# Generated by Django 5.2.5 on 2025-09-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_policydocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, help_text='A URL to the product image', max_length=500, null=True),
        ),
    ]
