# Generated by Django 5.2.5 on 2025-09-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_product_image_product_image_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='thread_type',
            field=models.CharField(choices=[('LIVE_SUPPORT', 'Live Support'), ('AI_ASSISTANT', 'AI Assistant')], default='LIVE_SUPPORT', max_length=20),
        ),
    ]
