# Generated by Django 5.2.5 on 2025-09-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_chatthread_thread_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='name',
            field=models.CharField(blank=True, help_text='An optional name for the chat thread', max_length=255, null=True),
        ),
    ]
