# kubernetes/1_backend-deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: eshop-prod
spec:
  replicas: 2 # Start with 2 pods for high availability
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        # IMPORTANT: Replace 'yourusername/eshop-backend:latest' with the actual name
        # of your image in your container registry (e.g., Docker Hub, GCR).
        image: Tilak-Vasu/eshop-backend:latest
        ports:
        - containerPort: 8000
        # Define resource requests and limits for better scheduling and stability
        resources:
          requests:
            cpu: "250m" # 0.25 CPU core
            memory: "256Mi"
          limits:
            cpu: "500m" # 0.5 CPU core
            memory: "512Mi"
        # In a real setup, you would use Kubernetes Secrets for your .env file
        # For now, this is a placeholder. You'd mount a Secret as a volume or env variables.
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "backend.settings"
        - name: GEMINI_API_KEY
          value: "your-gemini-key-from-a-secret"