# api/urls.py

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import TokenRefreshView

# Import all your views
from .views import (
    CreateUserView,
    MyTokenObtainPairView,
    ProductViewSet,
    CategoryListView,
    LikedProductView,
    LikedProductListView,
    OrderListCreateView,
    AdminDashboardView,
    ChatThreadView,
    CreatePaymentIntentView  # <-- The view for payments
)

# Create a router for the ProductViewSet
router = DefaultRouter()
# This one line automatically creates the URLs for:
# - Listing all products (GET /api/products/)
# - Creating a new product (POST /api/products/)
# - Retrieving a single product (GET /api/products/<id>/)
# - Updating a product (PUT/PATCH /api/products/<id>/)
# - Deleting a product (DELETE /api/products/<id>/)
router.register(r'products', ProductViewSet, basename='product')


# Define all the application's URL patterns
urlpatterns = [
    # --- AUTHENTICATION ---
    path('register/', CreateUserView.as_view(), name='register'),
    path('token/', MyTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    # --- PRODUCTS, CATEGORIES, & LIKES ---
    path('categories/', CategoryListView.as_view(), name='category-list'),
    path('products/like/', LikedProductView.as_view(), name='product-like-toggle'),
    path('products/liked/', LikedProductListView.as_view(), name='liked-product-list'),

    # --- ORDERS & CHECKOUT ---
    path('orders/', OrderListCreateView.as_view(), name='order-list-create'),
    # --- THIS IS THE CORRECTED LINE ---
    path('create-payment-intent/', CreatePaymentIntentView.as_view(), name='create-payment-intent'),

    # --- CHAT ---
    path('chat_threads/', ChatThreadView.as_view(), name='chat-thread-list'),
    
    # --- ADMIN ---
    path('admin/dashboard/', AdminDashboardView.as_view(), name='admin-dashboard'),

    # --- ROUTER URLS ---
    # This must be the last item in the list for the paths to resolve correctly.
    # It includes all the URLs automatically generated by the router (e.g., for products).
    path('', include(router.urls)),
]