# .github/workflows/ci.yml

name: E-Shop CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Grant permission for the job to write to GHCR

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # --- THIS IS THE CORRECTED LOGIN STEP ---
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          # Best Practice: Use github.actor to dynamically get the username of the person who triggered the workflow.
          # This avoids needing a separate GH_USERNAME secret.
          username: ${{ github.actor }}
          # The syntax for the password secret is correct as is.
          password: ${{ secrets.GH_PAT }}

      # --- THIS IS THE CORRECTED BUILD/PUSH STEP for Backend ---
      - name: Build and push Backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          # We use github.actor here as well to ensure the image tag is correct.
          tags: ghcr.io/${{ github.actor }}/eshop-backend:latest

      # --- THIS IS THE CORRECTED BUILD/PUSH STEP for Frontend ---
      - name: Build and push Frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ghcr.io/${{ github.actor }}/eshop-frontend:latest